version: 2
jobs:
  build:
    docker:
      - image: atsnngs/heroku-nodejs-ci:latest
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm test
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master